### PR TITLE
Added --quite to all module purge calls

### PR DESCRIPTION
**Pull request by mathiasbockwoldt**
to suppress unnecessary/confusing warnings in log in all script files

### CODE REVIEW

**Comment by bast** [comment]
Is it `--quiet`?

**Comment by mathiasbockwoldt** [comment]
Yes, from a typographic point of view, you are right. Funnily, `module` suppressed all warnings even with the typo... But I will correct this error later today :)

**Comment by bast** [comment]
No need to close it, you can add the correction to this PR and keep it open.

**Comment by mathiasbockwoldt** [comment]
... Yes of course, that would have been the better way. I saw your message too late and opened a new PR. Next time 😃

**Pull request closed without merging**
