### PR TITLE
Update writing-support-requests.rst

### PR DESCRIPTION
**Pull request by sventor**
... with what we see a lot in our HPC environment: users sending _pictures_ (!) of their `ssh` window, instead of text-based c&p.
And remind users to not treat us as "LMGTFY slaves"...

Cheers from Darmstadt/Germany!

### CODE REVIEW

**Comment by sventor** [comment]
Hi Radovan,

beside being on GitHub (and thus apparently OpenSource): would you mind if we take your (excellent) text and use it on our websites, too...?

If you wanna have a look: https://www.hhlr.tu-darmstadt.de/hhlr/index.en.jsp and (more general for the german HPC community) https://hpc-wiki.info/hpc/HPC_Wiki

Thanks a lot and all the best!

**Comment by bast** [comment]
dear Christian, reuse is absolutely welcome and really appreciated. I am adding a TODO item for myself to soon give the text a CC-type license to make reuse easier in future.

BTW you or your colleagues might be interested in this event that I am co-organizing: https://nordichpc.github.io/2019-11-14-helsinki/

**Comment by sventor** [comment]
Great - thanks a lot!!

**Comment by bast** [comment]
CC-BY is on the way: https://github.com/uit-no/hpc-doc/pull/69

**Pull request merged**
